# Generated by Django 5.2.7 on 2025-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='datasheet',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
