# Generated by Django 5.2.7 on 2025-11-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='equipment',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheets/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Short description or usage of the equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
