# Generated by Django 5.2.7 on 2025-11-27 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_borrow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_borrow_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
