# Generated by Django 5.2.7 on 2025-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_usagerecord_approved_by_usagerecord_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='damage_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
