# Generated by Django 5.2.7 on 2025-11-27 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_usagerecord_damage_report_usagerecord_is_damaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagerecord',
            name='purpose',
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='damage_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='borrowed_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='quantity_used',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
