# Generated by Django 5.2.7 on 2025-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_usagerecord_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='equipments_available',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
